### ISSUE TITLE
It seems like there is a ignored value in delta calculation?

### ISSUE THREAD

**Issue by rikoras** [hiyouga/FastEdit#28]
https://github.com/hiyouga/FastEdit/blob/76a8cf62a80d1017caeb5daca2b8cce5755f24ae/fastedit/rome/compute_u.py#L73-L82

I noticed that `get_inv_cov` is not implemented, and this value is correspond to this constant _C_ in original paper:
![图片](https://github.com/hiyouga/FastEdit/assets/28751316/93ce6ece-a8fc-49cb-b2f7-f02a09b45a66)

And for this code snippet:
https://github.com/hiyouga/FastEdit/blob/76a8cf62a80d1017caeb5daca2b8cce5755f24ae/fastedit/rome/compute_v.py#L156

Calculation of _Λ_ just ignore this constant. 
**In my experiments, this may lead to a small part of edit fail to apply.** 

I wonder why left `get_inv_cov` function unimplemented. If it is tricky, is there an alternate solution, like directly adding constants for each model into hyperparams?

Looking forward for your reply.🙂

**Comment by hiyouga** [comment]
We didn't add this constant because it needs to be computed for each model on the wiki data, reducing the convenience of the library. We also found that removing it does not significantly affect the effectiveness of the Rome algorithm. Nevertheless, adding a hyperparameter to provide the value of this constant should be a better choice.

**Comment by rikoras** [comment]
I see. For now, is there any ready-made constant? If not, I think I may check the original Rome code to compute them by myself.

**Comment by hiyouga** [comment]
we haven't the computed parameters, please refer to the original implementation
